title: Scholaricons
release: 1.0.0
author: Trey Saddler
email: treyosaddler@gmail.com
description: >
  Scholaricons is licensed under the <a href="http://scripts.sil.org/OFL">SIL OFL 1.1 license</a> •  This page was built using <a href="https://jekyllrb.com/">Jekyll</a> (theme: <a href="https://github.com/jekyll/minima">minima</a>), and uses code from <a href="http://simplegrid.io/">Simple Grid</a> • Request new icons by <a href="https://github.com/treysaddler/scholaricons/issues">creating an issue</a> on the GitHub repository
baseurl: "/scholaricons"
url: "https://treysaddler.github.io"
github_username: treysaddler

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
