name: Build Scholaricons Fonts
on:
  push:
    branches: master
    paths:
      - 'svg/monochrome/**'
      - 'fontcustom.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontforge woff2 eot-utils

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install FontCustom
        run: gem install fontcustom

      - name: Compile Fonts
        run: fontcustom compile

      - name: Install Minifier
        run: npm install -g clean-css-cli

      - name: Compile Fonts
        run: fontcustom compile

      - name: Minify CSS
        run: cleancss -o css/scholaricons.min.css css/scholaricons.css

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild scholaricons fonts, css, and min.css"
          file_pattern: 'fonts/* css/*'
